services:
  db:
    image: postgres:latest
    container_name: postgres-job-board
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5443:5432"  # host:container mapping
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - jobboard-net
    restart: unless-stopped
networks:
  jobboard-net:
    driver: bridge

volumes:
  db:

